source 'https://rubygems.org'

# use our own fork for bulk load support until issue fixed:
# https://github.com/brianmario/mysql2/pull/242
gem 'mysql2', :git => 'git://github.com/activewarehouse/mysql2.git'

gem 'activewarehouse-etl', '1.0.0'
gem 'adapter_extensions', '1.0.0'
gem 'awesome_print'

group :test do
  gem 'rspec'
end
